package headers

const (
	FLUTE_DATA_BODY_PACKET byte = 0x03
	FLUTE_DATA_HEAD_PACKET byte = 0x08
	FLUTE_DATA_XMLD_PACKET byte = 0x0b
)

const (
	FLUTE_BASE_HEADER_LEN                        = 16
	FLUTE_TIME_HEADER_SUP_LEN                    = 8
	FLUTE_DATA_HEADER_SUP_LEN                    = 0
	FLUTE_DATA_XML_DESCRIPTOR_HEADER_SUP_LEN     = 20
	FLUTE_DATA_XML_DESCRIPTOR_HEADER_SUP_LEN_ALT = FLUTE_DATA_XML_DESCRIPTOR_HEADER_SUP_LEN + 12
	FLUTE_CONF_HEADER_SUP_LEN                    = 8
	FLUTE_DATA_XML_DESCRIPTOR                    = FLUTE_DATA_HEAD_PACKET
	FLUTE_DATA_FILE_DESCRIPTOR                   = FLUTE_DATA_BODY_PACKET
	FLUTE_DATA_XML_DESCRIPTOR_ALT                = FLUTE_DATA_XMLD_PACKET
)
